apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkdock-deployment
  labels: 
    app: nkdock
spec:
  replicas:
  selector:
    matchLabels:
      app: nkdock
  template:
    metadata:
      labels:
        app: nkdock
    spec:
      containers:
      - name: nkdock2
        image: nkdock2:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        


